[project]
name = "decisioncenter-mcp-server"
version = "0.1.0"
description = "An MCP Server to integrate with IBM ODM Decision Center"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonref",
    "mcp>=2.0.0,<3",
    "openapi3-parser",
    "pyjwt",
    "python-multipart",
    "pyyaml",
    "requests",
    "starlette",
    "validator_collection",
]

[project.optional-dependencies]
default = [
    "cryptography>=50.0.0",
]
s390x = [
    "cryptography==36.0.1",
]

[tool.uv]
conflicts = [
    [
        { extra = "default" },
        { extra = "s390x" },
    ],
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-html",
    "responses",
]

[[project.authors]]
name = "Frederic Mercier"
email = "f.mercier@fr.ibm.com"

[build-system]
requires = [ "uv_build>=0.8.5,<0.9.0",]
build-backend = "uv_build"

[project.scripts]
ibm-odm-management-mcp-server = "decisioncenter_mcp_server:main"
decisioncenter-mcp-server = "decisioncenter_mcp_server:main"
